steps:
# The code
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/williamtsoi1/gcp-tweets-streaming-pipeline.git']

# App Engine ('beta' for live debugging)
- name: gcr.io/cloud-builders/gcloud
  args: ['beta', 'app', 'deploy', '--version=tweets']
  dir: 'twitter-to-pubsub'

# Dataflow pipeline
- name: gcr.io/cloud-builders/gradle
  args: ['run']

timeout: 1800s
